 name: Clean Actions GitHub Cache

 on:
  schedule:
    - cron: 0 8 * * *
  workflow_dispatch:

 jobs:
   clean:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Run cleaner script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./scripts/delete-unused-cache.sh
          ./scripts/delete-unused-cache.sh
